// <auto-generated />
using System;
using CwAssetManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CwAssetManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CwAssetManager.Core.Models.AssetEvaluation", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<double>("ComplianceScore").HasColumnType("REAL");
                b.Property<DateTimeOffset>("EvaluatedAt").HasColumnType("TEXT");
                b.Property<double>("HealthScore").HasColumnType("REAL");
                b.Property<Guid>("MachineId").HasColumnType("TEXT");
                b.Property<string>("Notes").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("MachineId");
                b.ToTable("AssetEvaluations");
            });

            modelBuilder.Entity("CwAssetManager.Core.Models.Machine", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<string>("BiosGuid").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("CwControlSessionId").HasMaxLength(128).HasColumnType("TEXT");
                b.Property<string>("CwManageDeviceId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("CwRmmDeviceId").HasMaxLength(128).HasColumnType("TEXT");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Hostname").HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<DateTimeOffset>("LastSeen").HasColumnType("TEXT");
                b.Property<string>("MacAddress").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<string>("OperatingSystem").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("SerialNumber").HasMaxLength(128).HasColumnType("TEXT");
                b.Property<int>("Status").HasColumnType("INTEGER");
                b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Hostname");
                b.HasIndex("MacAddress");
                b.HasIndex("SerialNumber");
                b.ToTable("Machines");
            });

            modelBuilder.Entity("CwAssetManager.Core.Models.ProviderConfig", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<string>("BaseUrl").IsRequired().HasMaxLength(512).HasColumnType("TEXT");
                b.Property<int>("BurstCapacity").HasColumnType("INTEGER");
                b.Property<bool>("IsEnabled").HasColumnType("INTEGER");
                b.Property<int>("Provider").HasColumnType("INTEGER");
                b.Property<int>("RequestsPerMinute").HasColumnType("INTEGER");
                b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("ProviderConfigs");
            });

            modelBuilder.Entity("CwAssetManager.Data.RequestLog", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<string>("CorrelationId").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<long>("DurationMs").HasColumnType("INTEGER");
                b.Property<string>("ErrorMessage").HasColumnType("TEXT");
                b.Property<string>("Method").IsRequired().HasMaxLength(16).HasColumnType("TEXT");
                b.Property<string>("Provider").IsRequired().HasColumnType("TEXT");
                b.Property<string>("RequestBody").HasColumnType("TEXT");
                b.Property<string>("ResponseBody").HasColumnType("TEXT");
                b.Property<int>("StatusCode").HasColumnType("INTEGER");
                b.Property<DateTimeOffset>("Timestamp").HasColumnType("TEXT");
                b.Property<string>("Url").IsRequired().HasMaxLength(2048).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Provider");
                b.HasIndex("Timestamp");
                b.ToTable("RequestLogs");
            });

            modelBuilder.Entity("CwAssetManager.Core.Models.AssetEvaluation", b =>
            {
                b.HasOne("CwAssetManager.Core.Models.Machine", "Machine")
                    .WithMany("Evaluations")
                    .HasForeignKey("MachineId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Machine");
            });

            modelBuilder.Entity("CwAssetManager.Core.Models.Machine", b =>
            {
                b.Navigation("Evaluations");
            });
#pragma warning restore 612, 618
        }
    }
}
